2024-03-19 09:18:11,340 - distributed.nanny - INFO -         Start Nanny at: 'tcp://192.41.104.190:41259'
2024-03-19 09:18:20,633 - distributed.worker - INFO -       Start worker at: tcp://192.41.104.190:37249
2024-03-19 09:18:20,634 - distributed.worker - INFO -          Listening to: tcp://192.41.104.190:37249
2024-03-19 09:18:20,634 - distributed.worker - INFO -           Worker name:               SGECluster-2
2024-03-19 09:18:20,634 - distributed.worker - INFO -          dashboard at:       192.41.104.190:46869
2024-03-19 09:18:20,635 - distributed.worker - INFO - Waiting to connect to:  tcp://192.41.105.80:46517
2024-03-19 09:18:20,635 - distributed.worker - INFO - -------------------------------------------------
2024-03-19 09:18:20,635 - distributed.worker - INFO -               Threads:                          1
2024-03-19 09:18:20,635 - distributed.worker - INFO -                Memory:                   7.45 GiB
2024-03-19 09:18:20,635 - distributed.worker - INFO -       Local Directory: /local/41764478.1.eddie/dask-scratch-space/worker-3s9hdjeu
2024-03-19 09:18:20,635 - distributed.worker - INFO - -------------------------------------------------
2024-03-19 09:18:22,063 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-03-19 09:18:22,064 - distributed.worker - INFO -         Registered to:  tcp://192.41.105.80:46517
2024-03-19 09:18:22,064 - distributed.worker - INFO - -------------------------------------------------
2024-03-19 09:18:22,065 - distributed.core - INFO - Starting established connection to tcp://192.41.105.80:46517
2024-03-19 09:35:23,417 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.25s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/home/s2211259/khamseh-lab/scematk/env/lib/python3.12/site-packages/dask/core.py:127: RuntimeWarning: divide by zero encountered in log10
  return func(*(_execute_task(a, cache) for a in args))
2024-03-19 09:43:51,324 - distributed.worker - INFO - Closing worker gracefully: tcp://192.41.104.190:37249. Reason: worker-lifetime-reached
2024-03-19 09:43:51,371 - distributed.worker - INFO - Stopping worker at tcp://192.41.104.190:37249. Reason: worker-lifetime-reached
2024-03-19 09:43:51,376 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://192.41.104.190:41259'. Reason: worker-lifetime-reached
2024-03-19 09:43:51,388 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home/s2211259/khamseh-lab/scematk/env/lib/python3.12/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nosplit_nbytes_bin = await stream.read_bytes(fmt_size)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/s2211259/khamseh-lab/scematk/env/lib/python3.12/site-packages/distributed/worker.py", line 1252, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2211259/khamseh-lab/scematk/env/lib/python3.12/site-packages/distributed/utils_comm.py", line 455, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
  File "/home/s2211259/khamseh-lab/scematk/env/lib/python3.12/site-packages/distributed/utils_comm.py", line 434, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home/s2211259/khamseh-lab/scematk/env/lib/python3.12/site-packages/distributed/core.py", line 1395, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2211259/khamseh-lab/scematk/env/lib/python3.12/site-packages/distributed/core.py", line 1154, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2211259/khamseh-lab/scematk/env/lib/python3.12/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
  File "/home/s2211259/khamseh-lab/scematk/env/lib/python3.12/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://192.41.104.190:36656 remote=tcp://192.41.105.80:46517>: Stream is closed
2024-03-19 09:43:51,393 - distributed.core - INFO - Connection to tcp://192.41.105.80:46517 has been closed.
2024-03-19 09:43:51,395 - distributed.nanny - INFO - Worker closed
2024-03-19 09:43:53,716 - distributed.nanny - INFO - Closing Nanny at 'tcp://192.41.104.190:41259'. Reason: nanny-close-gracefully
2024-03-19 09:43:53,717 - distributed.dask_worker - INFO - End worker
